apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: log-test-stateful-0-snapshot-1
  annotations:
    portworx/snapshot-type: cloud
    #portworx/cloud-cred-id: (credential uuid) # This specifies the credentials UUID to use. Required is using multiple cloud providers. In a situation where a single cloud provider is configured with credentials that are already created, this is not required.
spec:
  persistentVolumeClaimName: datelog-test-stateful-0
